package cn.enaium.crystaldiskmark

/**
 * i18n: mirrors the reference .lang INI files.
 * Keys are "section.key". Missing keys fall back to English.
 */
object Lang {

    val languages = listOf(
        LangDef("en", "English"),
        LangDef("ja", "日本語"),
        LangDef("zh-CN", "简体中文"),
        LangDef("zh-TW", "繁體中文"),
        LangDef("ko", "한국어"),
        LangDef("fr", "Français"),
        LangDef("de", "Deutsch"),
        LangDef("es", "Español"),
        LangDef("it", "Italiano"),
        LangDef("pt", "Português"),
        LangDef("ru", "Русский"),
    )

    data class LangDef(val code: String, val displayName: String)

    var current: String = "en"

    private val fallback: Map<String, String> by lazy { english }

    private val translations: Map<String, Map<String, String>> by lazy {
        mapOf(
            "en" to english,
            "ja" to japanese,
            "zh-CN" to chineseSimplified,
            "zh-TW" to chineseTraditional,
            "ko" to korean,
            "fr" to french,
            "de" to german,
            "es" to spanish,
            "it" to italian,
            "pt" to portuguese,
            "ru" to russian,
        )
    }

    fun t(key: String): String {
        val map = translations[current] ?: return fallback[key] ?: key
        return map[key] ?: fallback[key] ?: key
    }

    /**
     * Every character that can appear in any of the bundled translations,
     * plus the language display names. Used to build a compact glyph range
     * list for the font atlas (instead of the huge full-CJK ranges).
     */
    fun allTranslatedChars(): Set<Char> {
        val chars = mutableSetOf<Char>()
        for ((code, map) in translations) {
            for (v in map.values) {
                for (c in v) chars.add(c)
            }
            languages.firstOrNull { it.code == code }?.let { for (c in it.displayName) chars.add(c) }
        }
        for (c in "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789()[]{}.,:;!?%+-*/=<>@_#&|~^'\"` \t") {
            chars.add(c)
        }
        return chars
    }

    // ------------------------------------------------------------------
    // English (fallback)
    // ------------------------------------------------------------------
    private val english = mapOf(
        "Menu.FILE" to "File",
        "Menu.SETTINGS" to "Settings",
        "Menu.PROFILE" to "Profile",
        "Menu.THEME" to "Theme",
        "Theme.DARK" to "Dark",
        "Theme.LIGHT" to "Light",
        "Theme.CLASSIC" to "Classic",
        "Menu.HELP" to "Help",
        "Menu.LANGUAGE" to "Language",
        "Menu.FILE_EXIT" to "Exit",
        "Menu.SAVE_TEXT" to "Save (text)",
        "Menu.SAVE_IMAGE" to "Save (image)",
        "Menu.EDIT_COPY" to "Copy",
        "Menu.TEST_DATA" to "Test Mode",
        "Menu.DEFAULT_RANDOM" to "Default (Random)",
        "Menu.ALL_ZERO" to "All 0x00 (0 Fill)",
        "Menu.SETTINGS_QUEUESTHREADS" to "Settings",
        "Menu.PROFILE_DEFAULT" to "Default",
        "Menu.PROFILE_PEAK" to "Peak Performance",
        "Menu.PROFILE_REAL" to "Real World Performance",
        "Menu.PROFILE_DEMO" to "Demonstration",
        "Menu.PROFILE_DEFAULT_MIX" to "Default w/MIX",
        "Menu.PROFILE_PEAK_MIX" to "Peak Performance w/ MIX",
        "Menu.PROFILE_REAL_MIX" to "Real World Performance w/ MIX",
        "Menu.BENCHMARK_READ_WRITE" to "Read&Write [+Mix]",
        "Menu.BENCHMARK_READ_ONLY" to "Read [+Mix]",
        "Menu.BENCHMARK_WRITE_ONLY" to "Write [+Mix]",
        "Menu.ZOOM" to "Zoom",
        "Menu.AUTO" to "Auto",
        "Menu.FONT_SETTING" to "Font Setting",
        "Menu.HELP_ABOUT" to "About CrystalDiskMark",
        "Menu.CRYSTALDEWWORLD" to "Crystal Dew World [Web]",
        "Menu.HELP_HELP" to "Help",
        "Menu.SELECT_FOLDER" to "Select Folder...",
        "Dialog.TYPE" to "Type",
        "Dialog.BLOCK_SIZE" to "Size",
        "Dialog.QUEUES" to "Queues",
        "Dialog.THREADS" to "Threads",
        "Dialog.MEASURE_TIME" to "Measure Time",
        "Dialog.INTERVAL_TIME" to "Interval Time",
        "Dialog.DEFAULT" to "Default",
        "Dialog.PROFILE_DEFAULT" to "Default",
        "Dialog.PROFILE_PEAK_PERFORMANCE" to "Peak Performance",
        "Dialog.PROFILE_DEMO" to "Demo",
        "WindowTitle.ABOUT" to "About",
        "WindowTitle.SETTINGS" to "Settings",
        "Title.TEST_COUNT" to "Test Count",
        "Title.TEST_SIZE" to "Test Size",
        "Title.TEST_DRIVE" to "Test Drive",
        "Title.TEST_UNIT" to "Test Unit",
        "Message.STOP_BENCHMARK" to "Benchmark is running.\nPlease stop the benchmark first.",
        "Message.DISK_CAPACITY_ERROR" to "Not enough disk space.",
        "Message.DISK_CREATE_FILE_ERROR" to "Failed to create the test file.",
        "Message.DISK_WRITE_ERROR" to "Failed to write to the test file.",
        "Message.DISK_READ_ERROR" to "Failed to read from the test file.",
    )

    private val japanese = mapOf(
        "Menu.FILE" to "ファイル",
        "Menu.SETTINGS" to "設定",
        "Menu.PROFILE" to "プロファイル",
        "Menu.THEME" to "テーマ",
        "Menu.HELP" to "ヘルプ",
        "Menu.LANGUAGE" to "言語",
        "Menu.FILE_EXIT" to "終了",
        "Menu.SAVE_TEXT" to "テキスト保存",
        "Menu.SAVE_IMAGE" to "画像保存",
        "Menu.EDIT_COPY" to "コピー",
        "Menu.TEST_DATA" to "テストデータ",
        "Menu.DEFAULT_RANDOM" to "既定 (ランダム)",
        "Menu.ALL_ZERO" to "全て 0x00 (0 フィル)",
        "Menu.SETTINGS_QUEUESTHREADS" to "設定",
        "Menu.PROFILE_DEFAULT" to "既定",
        "Menu.PROFILE_PEAK" to "ピークパフォーマンス",
        "Menu.PROFILE_REAL" to "実用パフォーマンス",
        "Menu.PROFILE_DEMO" to "デモ",
        "Menu.PROFILE_DEFAULT_MIX" to "既定 w/MIX",
        "Menu.PROFILE_PEAK_MIX" to "ピークパフォーマンス w/ MIX",
        "Menu.PROFILE_REAL_MIX" to "実用パフォーマンス w/ MIX",
        "Menu.BENCHMARK_READ_WRITE" to "読み書き [+MIX]",
        "Menu.BENCHMARK_READ_ONLY" to "読み取り [+MIX]",
        "Menu.BENCHMARK_WRITE_ONLY" to "書き込み [+MIX]",
        "Menu.ZOOM" to "ズーム",
        "Menu.AUTO" to "自動",
        "Menu.FONT_SETTING" to "フォント設定",
        "Menu.HELP_ABOUT" to "CrystalDiskMark について",
        "Menu.CRYSTALDEWWORLD" to "Crystal Dew World [Web]",
        "Menu.HELP_HELP" to "ヘルプ",
        "Menu.SELECT_FOLDER" to "フォルダを選択...",
        "Dialog.TYPE" to "種別",
        "Dialog.BLOCK_SIZE" to "サイズ",
        "Dialog.QUEUES" to "キュー",
        "Dialog.THREADS" to "スレッド",
        "Dialog.MEASURE_TIME" to "測定時間",
        "Dialog.INTERVAL_TIME" to "インターバル",
        "Dialog.DEFAULT" to "既定",
        "Dialog.PROFILE_DEFAULT" to "既定",
        "Dialog.PROFILE_PEAK_PERFORMANCE" to "ピークパフォーマンス",
        "Dialog.PROFILE_DEMO" to "デモ",
        "WindowTitle.ABOUT" to "バージョン情報",
        "WindowTitle.SETTINGS" to "設定",
        "Title.TEST_COUNT" to "テスト回数",
        "Title.TEST_SIZE" to "テストサイズ",
        "Title.TEST_DRIVE" to "テストドライブ",
        "Title.TEST_UNIT" to "テスト単位",
        "Message.STOP_BENCHMARK" to "ベンチマーク実行中です。\n先にベンチマークを停止してください。",
        "Message.DISK_CAPACITY_ERROR" to "ディスクの空き容量が不足しています。",
        "Message.DISK_CREATE_FILE_ERROR" to "テストファイルの作成に失敗しました。",
        "Message.DISK_WRITE_ERROR" to "テストファイルへの書き込みに失敗しました。",
        "Message.DISK_READ_ERROR" to "テストファイルの読み込みに失敗しました。",
    )

    private val chineseSimplified = mapOf(
        "Menu.FILE" to "文件",
        "Menu.SETTINGS" to "设置",
        "Menu.PROFILE" to "配置文件",
        "Menu.THEME" to "主题",
        "Menu.HELP" to "帮助",
        "Menu.LANGUAGE" to "语言",
        "Menu.FILE_EXIT" to "退出",
        "Menu.SAVE_TEXT" to "保存文本",
        "Menu.SAVE_IMAGE" to "保存图像",
        "Menu.EDIT_COPY" to "复制",
        "Menu.TEST_DATA" to "测试数据",
        "Menu.DEFAULT_RANDOM" to "默认(随机)",
        "Menu.ALL_ZERO" to "全部 0x00 (0 填充)",
        "Menu.SETTINGS_QUEUESTHREADS" to "设置",
        "Menu.PROFILE_DEFAULT" to "默认",
        "Menu.PROFILE_PEAK" to "峰值性能",
        "Menu.PROFILE_REAL" to "实际性能",
        "Menu.PROFILE_DEMO" to "演示",
        "Menu.PROFILE_DEFAULT_MIX" to "默认 w/MIX",
        "Menu.PROFILE_PEAK_MIX" to "峰值性能 w/ MIX",
        "Menu.PROFILE_REAL_MIX" to "实际性能 w/ MIX",
        "Menu.BENCHMARK_READ_WRITE" to "读写 [+MIX]",
        "Menu.BENCHMARK_READ_ONLY" to "读取 [+MIX]",
        "Menu.BENCHMARK_WRITE_ONLY" to "写入 [+MIX]",
        "Menu.ZOOM" to "缩放",
        "Menu.AUTO" to "自动",
        "Menu.FONT_SETTING" to "字体设置",
        "Menu.HELP_ABOUT" to "关于 CrystalDiskMark",
        "Menu.CRYSTALDEWWORLD" to "Crystal Dew World [Web]",
        "Menu.HELP_HELP" to "帮助",
        "Menu.SELECT_FOLDER" to "选择文件夹...",
        "Dialog.TYPE" to "类型",
        "Dialog.BLOCK_SIZE" to "大小",
        "Dialog.QUEUES" to "队列",
        "Dialog.THREADS" to "线程",
        "Dialog.MEASURE_TIME" to "测量时间",
        "Dialog.INTERVAL_TIME" to "间隔时间",
        "Dialog.DEFAULT" to "默认",
        "Dialog.PROFILE_DEFAULT" to "默认",
        "Dialog.PROFILE_PEAK_PERFORMANCE" to "峰值性能",
        "Dialog.PROFILE_DEMO" to "演示",
        "WindowTitle.ABOUT" to "关于",
        "WindowTitle.SETTINGS" to "设置",
        "Title.TEST_COUNT" to "测试次数",
        "Title.TEST_SIZE" to "测试大小",
        "Title.TEST_DRIVE" to "测试驱动器",
        "Title.TEST_UNIT" to "测试单位",
        "Message.STOP_BENCHMARK" to "基准测试正在运行。\n请先停止基准测试。",
        "Message.DISK_CAPACITY_ERROR" to "磁盘空间不足。",
        "Message.DISK_CREATE_FILE_ERROR" to "创建测试文件失败。",
        "Message.DISK_WRITE_ERROR" to "写入测试文件失败。",
        "Message.DISK_READ_ERROR" to "读取测试文件失败。",
    )

    private val chineseTraditional = mapOf(
        "Menu.FILE" to "檔案",
        "Menu.SETTINGS" to "設定",
        "Menu.PROFILE" to "設定檔",
        "Menu.THEME" to "主題",
        "Menu.HELP" to "說明",
        "Menu.LANGUAGE" to "語言",
        "Menu.FILE_EXIT" to "結束",
        "Menu.SAVE_TEXT" to "儲存文字",
        "Menu.SAVE_IMAGE" to "儲存影像",
        "Menu.EDIT_COPY" to "複製",
        "Menu.TEST_DATA" to "測試資料",
        "Menu.DEFAULT_RANDOM" to "預設 (隨機)",
        "Menu.ALL_ZERO" to "全部 0x00 (0 填充)",
        "Menu.SETTINGS_QUEUESTHREADS" to "設定",
        "Menu.PROFILE_DEFAULT" to "預設",
        "Menu.PROFILE_PEAK" to "峰值效能",
        "Menu.PROFILE_REAL" to "實際效能",
        "Menu.PROFILE_DEMO" to "示範",
        "Menu.PROFILE_DEFAULT_MIX" to "預設 w/MIX",
        "Menu.PROFILE_PEAK_MIX" to "峰值效能 w/ MIX",
        "Menu.PROFILE_REAL_MIX" to "實際效能 w/ MIX",
        "Menu.BENCHMARK_READ_WRITE" to "讀寫 [+MIX]",
        "Menu.BENCHMARK_READ_ONLY" to "讀取 [+MIX]",
        "Menu.BENCHMARK_WRITE_ONLY" to "寫入 [+MIX]",
        "Menu.ZOOM" to "縮放",
        "Menu.AUTO" to "自動",
        "Menu.FONT_SETTING" to "字型設定",
        "Menu.HELP_ABOUT" to "關於 CrystalDiskMark",
        "Menu.CRYSTALDEWWORLD" to "Crystal Dew World [Web]",
        "Menu.HELP_HELP" to "說明",
        "Menu.SELECT_FOLDER" to "選擇資料夾...",
        "Dialog.TYPE" to "類型",
        "Dialog.BLOCK_SIZE" to "大小",
        "Dialog.QUEUES" to "佇列",
        "Dialog.THREADS" to "執行緒",
        "Dialog.MEASURE_TIME" to "測量時間",
        "Dialog.INTERVAL_TIME" to "間隔時間",
        "Dialog.DEFAULT" to "預設",
        "Dialog.PROFILE_DEFAULT" to "預設",
        "Dialog.PROFILE_PEAK_PERFORMANCE" to "峰值效能",
        "Dialog.PROFILE_DEMO" to "示範",
        "WindowTitle.ABOUT" to "關於",
        "WindowTitle.SETTINGS" to "設定",
        "Title.TEST_COUNT" to "測試次數",
        "Title.TEST_SIZE" to "測試大小",
        "Title.TEST_DRIVE" to "測試磁碟",
        "Title.TEST_UNIT" to "測試單位",
        "Message.STOP_BENCHMARK" to "基準測試正在執行。\n請先停止基準測試。",
        "Message.DISK_CAPACITY_ERROR" to "磁碟空間不足。",
        "Message.DISK_CREATE_FILE_ERROR" to "建立測試檔案失敗。",
        "Message.DISK_WRITE_ERROR" to "寫入測試檔案失敗。",
        "Message.DISK_READ_ERROR" to "讀取測試檔案失敗。",
    )

    private val korean = mapOf(
        "Menu.FILE" to "파일",
        "Menu.SETTINGS" to "설정",
        "Menu.PROFILE" to "프로필",
        "Menu.THEME" to "테마",
        "Menu.HELP" to "도움말",
        "Menu.LANGUAGE" to "언어",
        "Menu.FILE_EXIT" to "종료",
        "Menu.SAVE_TEXT" to "텍스트 저장",
        "Menu.SAVE_IMAGE" to "이미지 저장",
        "Menu.EDIT_COPY" to "복사",
        "Menu.TEST_DATA" to "테스트 데이터",
        "Menu.DEFAULT_RANDOM" to "기본 (무작위)",
        "Menu.ALL_ZERO" to "모두 0x00 (0 채움)",
        "Menu.SETTINGS_QUEUESTHREADS" to "설정",
        "Menu.PROFILE_DEFAULT" to "기본",
        "Menu.PROFILE_PEAK" to "최고 성능",
        "Menu.PROFILE_REAL" to "실사용 성능",
        "Menu.PROFILE_DEMO" to "데모",
        "Menu.PROFILE_DEFAULT_MIX" to "기본 w/MIX",
        "Menu.PROFILE_PEAK_MIX" to "최고 성능 w/ MIX",
        "Menu.PROFILE_REAL_MIX" to "실사용 성능 w/ MIX",
        "Menu.BENCHMARK_READ_WRITE" to "읽기/쓰기 [+MIX]",
        "Menu.BENCHMARK_READ_ONLY" to "읽기 [+MIX]",
        "Menu.BENCHMARK_WRITE_ONLY" to "쓰기 [+MIX]",
        "Menu.ZOOM" to "확대",
        "Menu.AUTO" to "자동",
        "Menu.FONT_SETTING" to "글꼴 설정",
        "Menu.HELP_ABOUT" to "CrystalDiskMark 정보",
        "Menu.CRYSTALDEWWORLD" to "Crystal Dew World [Web]",
        "Menu.HELP_HELP" to "도움말",
        "Menu.SELECT_FOLDER" to "폴더 선택...",
        "Dialog.TYPE" to "유형",
        "Dialog.BLOCK_SIZE" to "크기",
        "Dialog.QUEUES" to "큐",
        "Dialog.THREADS" to "스레드",
        "Dialog.MEASURE_TIME" to "측정 시간",
        "Dialog.INTERVAL_TIME" to "간격 시간",
        "Dialog.DEFAULT" to "기본",
        "Dialog.PROFILE_DEFAULT" to "기본",
        "Dialog.PROFILE_PEAK_PERFORMANCE" to "최고 성능",
        "Dialog.PROFILE_DEMO" to "데모",
        "WindowTitle.ABOUT" to "정보",
        "WindowTitle.SETTINGS" to "설정",
        "Title.TEST_COUNT" to "테스트 횟수",
        "Title.TEST_SIZE" to "테스트 크기",
        "Title.TEST_DRIVE" to "테스트 드라이브",
        "Title.TEST_UNIT" to "테스트 단위",
        "Message.STOP_BENCHMARK" to "벤치마크가 실행 중입니다.\n먼저 벤치마크를 중지하십시오.",
        "Message.DISK_CAPACITY_ERROR" to "디스크 공간이 부족합니다.",
        "Message.DISK_CREATE_FILE_ERROR" to "테스트 파일을 만들지 못했습니다.",
        "Message.DISK_WRITE_ERROR" to "테스트 파일에 쓰지 못했습니다.",
        "Message.DISK_READ_ERROR" to "테스트 파일을 읽지 못했습니다.",
    )

    private val french = mapOf(
        "Menu.FILE" to "Fichier",
        "Menu.SETTINGS" to "Paramètres",
        "Menu.PROFILE" to "Profil",
        "Menu.THEME" to "Thème",
        "Menu.HELP" to "Aide",
        "Menu.LANGUAGE" to "Langue",
        "Menu.FILE_EXIT" to "Quitter",
        "Menu.SAVE_TEXT" to "Enregistrer (texte)",
        "Menu.SAVE_IMAGE" to "Enregistrer (image)",
        "Menu.EDIT_COPY" to "Copier",
        "Menu.TEST_DATA" to "Mode de test",
        "Menu.DEFAULT_RANDOM" to "Défaut (aléatoire)",
        "Menu.ALL_ZERO" to "Tout 0x00 (0 remplissage)",
        "Menu.SETTINGS_QUEUESTHREADS" to "Paramètres",
        "Menu.PROFILE_DEFAULT" to "Défaut",
        "Menu.PROFILE_PEAK" to "Performances maximales",
        "Menu.PROFILE_REAL" to "Performances réelles",
        "Menu.PROFILE_DEMO" to "Démonstration",
        "Menu.PROFILE_DEFAULT_MIX" to "Défaut w/MIX",
        "Menu.PROFILE_PEAK_MIX" to "Performances maximales w/ MIX",
        "Menu.PROFILE_REAL_MIX" to "Performances réelles w/ MIX",
        "Menu.BENCHMARK_READ_WRITE" to "Lecture&écriture [+MIX]",
        "Menu.BENCHMARK_READ_ONLY" to "Lecture [+MIX]",
        "Menu.BENCHMARK_WRITE_ONLY" to "Écriture [+MIX]",
        "Menu.ZOOM" to "Zoom",
        "Menu.AUTO" to "Auto",
        "Menu.FONT_SETTING" to "Paramètres de police",
        "Menu.HELP_ABOUT" to "À propos de CrystalDiskMark",
        "Menu.CRYSTALDEWWORLD" to "Crystal Dew World [Web]",
        "Menu.HELP_HELP" to "Aide",
        "Menu.SELECT_FOLDER" to "Choisir un dossier...",
        "Dialog.TYPE" to "Type",
        "Dialog.BLOCK_SIZE" to "Taille",
        "Dialog.QUEUES" to "Files",
        "Dialog.THREADS" to "Threads",
        "Dialog.MEASURE_TIME" to "Temps de mesure",
        "Dialog.INTERVAL_TIME" to "Temps d'intervalle",
        "Dialog.DEFAULT" to "Défaut",
        "Dialog.PROFILE_DEFAULT" to "Défaut",
        "Dialog.PROFILE_PEAK_PERFORMANCE" to "Performances maximales",
        "Dialog.PROFILE_DEMO" to "Démo",
        "WindowTitle.ABOUT" to "À propos",
        "WindowTitle.SETTINGS" to "Paramètres",
        "Title.TEST_COUNT" to "Nombre de tests",
        "Title.TEST_SIZE" to "Taille de test",
        "Title.TEST_DRIVE" to "Disque de test",
        "Title.TEST_UNIT" to "Unité de test",
        "Message.STOP_BENCHMARK" to "Le benchmark est en cours.\nVeuillez d'abord l'arrêter.",
        "Message.DISK_CAPACITY_ERROR" to "Espace disque insuffisant.",
        "Message.DISK_CREATE_FILE_ERROR" to "Échec de la création du fichier de test.",
        "Message.DISK_WRITE_ERROR" to "Échec de l'écriture du fichier de test.",
        "Message.DISK_READ_ERROR" to "Échec de la lecture du fichier de test.",
    )

    private val german = mapOf(
        "Menu.FILE" to "Datei",
        "Menu.SETTINGS" to "Einstellungen",
        "Menu.PROFILE" to "Profil",
        "Menu.THEME" to "Design",
        "Menu.HELP" to "Hilfe",
        "Menu.LANGUAGE" to "Sprache",
        "Menu.FILE_EXIT" to "Beenden",
        "Menu.SAVE_TEXT" to "Speichern (Text)",
        "Menu.SAVE_IMAGE" to "Speichern (Bild)",
        "Menu.EDIT_COPY" to "Kopieren",
        "Menu.TEST_DATA" to "Testmodus",
        "Menu.DEFAULT_RANDOM" to "Standard (Zufall)",
        "Menu.ALL_ZERO" to "Alle 0x00 (0-Füllung)",
        "Menu.SETTINGS_QUEUESTHREADS" to "Einstellungen",
        "Menu.PROFILE_DEFAULT" to "Standard",
        "Menu.PROFILE_PEAK" to "Spitzenleistung",
        "Menu.PROFILE_REAL" to "Realwelt-Leistung",
        "Menu.PROFILE_DEMO" to "Demonstration",
        "Menu.PROFILE_DEFAULT_MIX" to "Standard w/MIX",
        "Menu.PROFILE_PEAK_MIX" to "Spitzenleistung w/ MIX",
        "Menu.PROFILE_REAL_MIX" to "Realwelt-Leistung w/ MIX",
        "Menu.BENCHMARK_READ_WRITE" to "Lesen&Schreiben [+MIX]",
        "Menu.BENCHMARK_READ_ONLY" to "Lesen [+MIX]",
        "Menu.BENCHMARK_WRITE_ONLY" to "Schreiben [+MIX]",
        "Menu.ZOOM" to "Zoom",
        "Menu.AUTO" to "Automatisch",
        "Menu.FONT_SETTING" to "Schrifteinstellung",
        "Menu.HELP_ABOUT" to "Über CrystalDiskMark",
        "Menu.CRYSTALDEWWORLD" to "Crystal Dew World [Web]",
        "Menu.HELP_HELP" to "Hilfe",
        "Menu.SELECT_FOLDER" to "Ordner wählen...",
        "Dialog.TYPE" to "Typ",
        "Dialog.BLOCK_SIZE" to "Größe",
        "Dialog.QUEUES" to "Warteschlangen",
        "Dialog.THREADS" to "Threads",
        "Dialog.MEASURE_TIME" to "Messzeit",
        "Dialog.INTERVAL_TIME" to "Intervallzeit",
        "Dialog.DEFAULT" to "Standard",
        "Dialog.PROFILE_DEFAULT" to "Standard",
        "Dialog.PROFILE_PEAK_PERFORMANCE" to "Spitzenleistung",
        "Dialog.PROFILE_DEMO" to "Demo",
        "WindowTitle.ABOUT" to "Über",
        "WindowTitle.SETTINGS" to "Einstellungen",
        "Title.TEST_COUNT" to "Testanzahl",
        "Title.TEST_SIZE" to "Testgröße",
        "Title.TEST_DRIVE" to "Testlaufwerk",
        "Title.TEST_UNIT" to "Testeinheit",
        "Message.STOP_BENCHMARK" to "Benchmark läuft.\nBitte zuerst den Benchmark stoppen.",
        "Message.DISK_CAPACITY_ERROR" to "Nicht genügend Speicherplatz.",
        "Message.DISK_CREATE_FILE_ERROR" to "Testdatei konnte nicht erstellt werden.",
        "Message.DISK_WRITE_ERROR" to "Schreiben in die Testdatei fehlgeschlagen.",
        "Message.DISK_READ_ERROR" to "Lesen der Testdatei fehlgeschlagen.",
    )

    private val spanish = mapOf(
        "Menu.FILE" to "Archivo",
        "Menu.SETTINGS" to "Configuración",
        "Menu.PROFILE" to "Perfil",
        "Menu.THEME" to "Tema",
        "Menu.HELP" to "Ayuda",
        "Menu.LANGUAGE" to "Idioma",
        "Menu.FILE_EXIT" to "Salir",
        "Menu.SAVE_TEXT" to "Guardar (texto)",
        "Menu.SAVE_IMAGE" to "Guardar (imagen)",
        "Menu.EDIT_COPY" to "Copiar",
        "Menu.TEST_DATA" to "Modo de prueba",
        "Menu.DEFAULT_RANDOM" to "Predeterminado (aleatorio)",
        "Menu.ALL_ZERO" to "Todo 0x00 (relleno 0)",
        "Menu.SETTINGS_QUEUESTHREADS" to "Configuración",
        "Menu.PROFILE_DEFAULT" to "Predeterminado",
        "Menu.PROFILE_PEAK" to "Rendimiento máximo",
        "Menu.PROFILE_REAL" to "Rendimiento real",
        "Menu.PROFILE_DEMO" to "Demostración",
        "Menu.PROFILE_DEFAULT_MIX" to "Predeterminado w/MIX",
        "Menu.PROFILE_PEAK_MIX" to "Rendimiento máximo w/ MIX",
        "Menu.PROFILE_REAL_MIX" to "Rendimiento real w/ MIX",
        "Menu.BENCHMARK_READ_WRITE" to "Lectura&escritura [+MIX]",
        "Menu.BENCHMARK_READ_ONLY" to "Lectura [+MIX]",
        "Menu.BENCHMARK_WRITE_ONLY" to "Escritura [+MIX]",
        "Menu.ZOOM" to "Zoom",
        "Menu.AUTO" to "Automático",
        "Menu.FONT_SETTING" to "Configuración de fuente",
        "Menu.HELP_ABOUT" to "Acerca de CrystalDiskMark",
        "Menu.CRYSTALDEWWORLD" to "Crystal Dew World [Web]",
        "Menu.HELP_HELP" to "Ayuda",
        "Menu.SELECT_FOLDER" to "Seleccionar carpeta...",
        "Dialog.TYPE" to "Tipo",
        "Dialog.BLOCK_SIZE" to "Tamaño",
        "Dialog.QUEUES" to "Colas",
        "Dialog.THREADS" to "Hilos",
        "Dialog.MEASURE_TIME" to "Tiempo de medición",
        "Dialog.INTERVAL_TIME" to "Tiempo de intervalo",
        "Dialog.DEFAULT" to "Predeterminado",
        "Dialog.PROFILE_DEFAULT" to "Predeterminado",
        "Dialog.PROFILE_PEAK_PERFORMANCE" to "Rendimiento máximo",
        "Dialog.PROFILE_DEMO" to "Demo",
        "WindowTitle.ABOUT" to "Acerca de",
        "WindowTitle.SETTINGS" to "Configuración",
        "Title.TEST_COUNT" to "Número de pruebas",
        "Title.TEST_SIZE" to "Tamaño de prueba",
        "Title.TEST_DRIVE" to "Unidad de prueba",
        "Title.TEST_UNIT" to "Unidad de prueba",
        "Message.STOP_BENCHMARK" to "El benchmark está en ejecución.\nDetenga el benchmark primero.",
        "Message.DISK_CAPACITY_ERROR" to "Espacio en disco insuficiente.",
        "Message.DISK_CREATE_FILE_ERROR" to "Error al crear el archivo de prueba.",
        "Message.DISK_WRITE_ERROR" to "Error al escribir el archivo de prueba.",
        "Message.DISK_READ_ERROR" to "Error al leer el archivo de prueba.",
    )

    private val italian = mapOf(
        "Menu.FILE" to "File",
        "Menu.SETTINGS" to "Impostazioni",
        "Menu.PROFILE" to "Profilo",
        "Menu.THEME" to "Tema",
        "Menu.HELP" to "Aiuto",
        "Menu.LANGUAGE" to "Lingua",
        "Menu.FILE_EXIT" to "Esci",
        "Menu.SAVE_TEXT" to "Salva (testo)",
        "Menu.SAVE_IMAGE" to "Salva (immagine)",
        "Menu.EDIT_COPY" to "Copia",
        "Menu.TEST_DATA" to "Modalità test",
        "Menu.DEFAULT_RANDOM" to "Predefinito (casuale)",
        "Menu.ALL_ZERO" to "Tutto 0x00 (riempimento 0)",
        "Menu.SETTINGS_QUEUESTHREADS" to "Impostazioni",
        "Menu.PROFILE_DEFAULT" to "Predefinito",
        "Menu.PROFILE_PEAK" to "Prestazioni massime",
        "Menu.PROFILE_REAL" to "Prestazioni reali",
        "Menu.PROFILE_DEMO" to "Dimostrazione",
        "Menu.PROFILE_DEFAULT_MIX" to "Predefinito w/MIX",
        "Menu.PROFILE_PEAK_MIX" to "Prestazioni massime w/ MIX",
        "Menu.PROFILE_REAL_MIX" to "Prestazioni reali w/ MIX",
        "Menu.BENCHMARK_READ_WRITE" to "Lettura&scrittura [+MIX]",
        "Menu.BENCHMARK_READ_ONLY" to "Lettura [+MIX]",
        "Menu.BENCHMARK_WRITE_ONLY" to "Scrittura [+MIX]",
        "Menu.ZOOM" to "Zoom",
        "Menu.AUTO" to "Automatico",
        "Menu.FONT_SETTING" to "Impostazioni carattere",
        "Menu.HELP_ABOUT" to "Informazioni su CrystalDiskMark",
        "Menu.CRYSTALDEWWORLD" to "Crystal Dew World [Web]",
        "Menu.HELP_HELP" to "Aiuto",
        "Menu.SELECT_FOLDER" to "Seleziona cartella...",
        "Dialog.TYPE" to "Tipo",
        "Dialog.BLOCK_SIZE" to "Dimensione",
        "Dialog.QUEUES" to "Code",
        "Dialog.THREADS" to "Thread",
        "Dialog.MEASURE_TIME" to "Tempo di misurazione",
        "Dialog.INTERVAL_TIME" to "Tempo di intervallo",
        "Dialog.DEFAULT" to "Predefinito",
        "Dialog.PROFILE_DEFAULT" to "Predefinito",
        "Dialog.PROFILE_PEAK_PERFORMANCE" to "Prestazioni massime",
        "Dialog.PROFILE_DEMO" to "Demo",
        "WindowTitle.ABOUT" to "Informazioni",
        "WindowTitle.SETTINGS" to "Impostazioni",
        "Title.TEST_COUNT" to "Numero di test",
        "Title.TEST_SIZE" to "Dimensione test",
        "Title.TEST_DRIVE" to "Unità di test",
        "Title.TEST_UNIT" to "Unità di test",
        "Message.STOP_BENCHMARK" to "Il benchmark è in esecuzione.\nFermare prima il benchmark.",
        "Message.DISK_CAPACITY_ERROR" to "Spazio su disco insufficiente.",
        "Message.DISK_CREATE_FILE_ERROR" to "Impossibile creare il file di test.",
        "Message.DISK_WRITE_ERROR" to "Impossibile scrivere il file di test.",
        "Message.DISK_READ_ERROR" to "Impossibile leggere il file di test.",
    )

    private val portuguese = mapOf(
        "Menu.FILE" to "Arquivo",
        "Menu.SETTINGS" to "Configurações",
        "Menu.PROFILE" to "Perfil",
        "Menu.THEME" to "Tema",
        "Menu.HELP" to "Ajuda",
        "Menu.LANGUAGE" to "Idioma",
        "Menu.FILE_EXIT" to "Sair",
        "Menu.SAVE_TEXT" to "Salvar (texto)",
        "Menu.SAVE_IMAGE" to "Salvar (imagem)",
        "Menu.EDIT_COPY" to "Copiar",
        "Menu.TEST_DATA" to "Modo de teste",
        "Menu.DEFAULT_RANDOM" to "Padrão (aleatório)",
        "Menu.ALL_ZERO" to "Tudo 0x00 (preenchimento 0)",
        "Menu.SETTINGS_QUEUESTHREADS" to "Configurações",
        "Menu.PROFILE_DEFAULT" to "Padrão",
        "Menu.PROFILE_PEAK" to "Desempenho máximo",
        "Menu.PROFILE_REAL" to "Desempenho real",
        "Menu.PROFILE_DEMO" to "Demonstração",
        "Menu.PROFILE_DEFAULT_MIX" to "Padrão w/MIX",
        "Menu.PROFILE_PEAK_MIX" to "Desempenho máximo w/ MIX",
        "Menu.PROFILE_REAL_MIX" to "Desempenho real w/ MIX",
        "Menu.BENCHMARK_READ_WRITE" to "Leitura&escrita [+MIX]",
        "Menu.BENCHMARK_READ_ONLY" to "Leitura [+MIX]",
        "Menu.BENCHMARK_WRITE_ONLY" to "Escrita [+MIX]",
        "Menu.ZOOM" to "Zoom",
        "Menu.AUTO" to "Automático",
        "Menu.FONT_SETTING" to "Configuração de fonte",
        "Menu.HELP_ABOUT" to "Sobre o CrystalDiskMark",
        "Menu.CRYSTALDEWWORLD" to "Crystal Dew World [Web]",
        "Menu.HELP_HELP" to "Ajuda",
        "Menu.SELECT_FOLDER" to "Selecionar pasta...",
        "Dialog.TYPE" to "Tipo",
        "Dialog.BLOCK_SIZE" to "Tamanho",
        "Dialog.QUEUES" to "Filas",
        "Dialog.THREADS" to "Threads",
        "Dialog.MEASURE_TIME" to "Tempo de medição",
        "Dialog.INTERVAL_TIME" to "Tempo de intervalo",
        "Dialog.DEFAULT" to "Padrão",
        "Dialog.PROFILE_DEFAULT" to "Padrão",
        "Dialog.PROFILE_PEAK_PERFORMANCE" to "Desempenho máximo",
        "Dialog.PROFILE_DEMO" to "Demo",
        "WindowTitle.ABOUT" to "Sobre",
        "WindowTitle.SETTINGS" to "Configurações",
        "Title.TEST_COUNT" to "Número de testes",
        "Title.TEST_SIZE" to "Tamanho do teste",
        "Title.TEST_DRIVE" to "Unidade de teste",
        "Title.TEST_UNIT" to "Unidade de teste",
        "Message.STOP_BENCHMARK" to "O benchmark está em execução.\nPare o benchmark primeiro.",
        "Message.DISK_CAPACITY_ERROR" to "Espaço em disco insuficiente.",
        "Message.DISK_CREATE_FILE_ERROR" to "Falha ao criar o arquivo de teste.",
        "Message.DISK_WRITE_ERROR" to "Falha ao gravar o arquivo de teste.",
        "Message.DISK_READ_ERROR" to "Falha ao ler o arquivo de teste.",
    )

    private val russian = mapOf(
        "Menu.FILE" to "Файл",
        "Menu.SETTINGS" to "Настройки",
        "Menu.PROFILE" to "Профиль",
        "Menu.THEME" to "Тема",
        "Menu.HELP" to "Справка",
        "Menu.LANGUAGE" to "Язык",
        "Menu.FILE_EXIT" to "Выход",
        "Menu.SAVE_TEXT" to "Сохранить (текст)",
        "Menu.SAVE_IMAGE" to "Сохранить (изображение)",
        "Menu.EDIT_COPY" to "Копировать",
        "Menu.TEST_DATA" to "Режим теста",
        "Menu.DEFAULT_RANDOM" to "По умолчанию (случайно)",
        "Menu.ALL_ZERO" to "Все 0x00 (заполнение 0)",
        "Menu.SETTINGS_QUEUESTHREADS" to "Настройки",
        "Menu.PROFILE_DEFAULT" to "По умолчанию",
        "Menu.PROFILE_PEAK" to "Максимальная производительность",
        "Menu.PROFILE_REAL" to "Реальная производительность",
        "Menu.PROFILE_DEMO" to "Демонстрация",
        "Menu.PROFILE_DEFAULT_MIX" to "По умолчанию w/MIX",
        "Menu.PROFILE_PEAK_MIX" to "Максимальная производительность w/ MIX",
        "Menu.PROFILE_REAL_MIX" to "Реальная производительность w/ MIX",
        "Menu.BENCHMARK_READ_WRITE" to "Чтение&запись [+MIX]",
        "Menu.BENCHMARK_READ_ONLY" to "Чтение [+MIX]",
        "Menu.BENCHMARK_WRITE_ONLY" to "Запись [+MIX]",
        "Menu.ZOOM" to "Масштаб",
        "Menu.AUTO" to "Авто",
        "Menu.FONT_SETTING" to "Настройка шрифта",
        "Menu.HELP_ABOUT" to "О CrystalDiskMark",
        "Menu.CRYSTALDEWWORLD" to "Crystal Dew World [Web]",
        "Menu.HELP_HELP" to "Справка",
        "Menu.SELECT_FOLDER" to "Выбрать папку...",
        "Dialog.TYPE" to "Тип",
        "Dialog.BLOCK_SIZE" to "Размер",
        "Dialog.QUEUES" to "Очереди",
        "Dialog.THREADS" to "Потоки",
        "Dialog.MEASURE_TIME" to "Время измерения",
        "Dialog.INTERVAL_TIME" to "Время интервала",
        "Dialog.DEFAULT" to "По умолчанию",
        "Dialog.PROFILE_DEFAULT" to "По умолчанию",
        "Dialog.PROFILE_PEAK_PERFORMANCE" to "Максимальная производительность",
        "Dialog.PROFILE_DEMO" to "Демо",
        "WindowTitle.ABOUT" to "О программе",
        "WindowTitle.SETTINGS" to "Настройки",
        "Title.TEST_COUNT" to "Количество тестов",
        "Title.TEST_SIZE" to "Размер теста",
        "Title.TEST_DRIVE" to "Тестовый диск",
        "Title.TEST_UNIT" to "Единица теста",
        "Message.STOP_BENCHMARK" to "Бенчмарк выполняется.\nСначала остановите бенчмарк.",
        "Message.DISK_CAPACITY_ERROR" to "Недостаточно места на диске.",
        "Message.DISK_CREATE_FILE_ERROR" to "Не удалось создать тестовый файл.",
        "Message.DISK_WRITE_ERROR" to "Не удалось записать тестовый файл.",
        "Message.DISK_READ_ERROR" to "Не удалось прочитать тестовый файл.",
    )
}
